type Directory {
  _id: String!
  name: String!
  father: String
  directories: [String]!
  files: [String]!
  owner: String!
  createdAt: DateTime!
  createdBy: String!
  modifiedAt: DateTime
  modifiedBy: String
  access: [Access]!
}

type RecursiveDirectory {
  _id: String!
  name: String!
  father: String
  directories: [RecursiveDirectory]!
  files: [File]!
  owner: String!
  createdAt: DateTime!
  createdBy: String!
  modifiedAt: DateTime
  modifiedBy: String
  access: [Access]!
}


type Query {
  directories(ids: [String]!): [Directory]!
  recursiveDirectories(ids: [String]!): [RecursiveDirectory]!
  userDirectories(id: String): [Directory]!
}

type Mutation {
  mkdir(name: String!, where: String!): Directory
  rmDir(id: String!): Directory
  changeDirName(id: String!, name: String!): Directory!
  changeDirFather(id: String!, newFather: String!): Directory!
  changeDirOwnership(id: String!, newOwner: String!): Directory!
  giveDirAccess(id: String!, who: String!, newAccess: LevelEnum): Directory!
  removeDirAccess(id: String!, who: String!): Directory!
}
