type Directory {
  _id: String!
  name: String!
  father: String
  directories: [String]!
  files: [String]!
  owner: String!
  createdAt: String!
  createdBy: String!
  modifiedAt: String
  modifiedBy: String
  access: [Access]!
}

type RecursiveDirectory {
  _id: String!
  name: String!
  father: String
  directories: [RecursiveDirectory]!
  files: [File]!
  owner: String!
  createdAt: String!
  createdBy: String!
  modifiedAt: String
  modifiedBy: String
  access: [Access]!
}


type Query {
  getDirs(ids: [String]!): [Directory]!
  getRecursiveDirs(ids: [String]!): [RecursiveDirectory]!
}

type Mutation {
  mkdir(name: String!, where: String!): Directory
  rmDir(id: String!): Directory
}
