# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: fbroot
      MONGO_INITDB_ROOT_PASSWORD: fbmongopass
      MONGO_INITDB_DATABASE: familly_bugget
    ports:
      - 27017:27017
