type File {
  _id: String!
  name: String!
  father: String!
  owner: String!
  createdAt: DateTime!
  createdBy: String!
  modifiedAt: DateTime
  modifiedBy: String
  access: [Access]!
}


type Query {
  getFilesInDirs(dirIds: [String]!): [File]!
}

type Mutation {
  touch(name: String!, where: String!): File
  rmFile(fileId: String!): File
}
