type File {
  _id: String!
  name: String!
  father: String!
  owner: String!
  createdAt: String!
  createdBy: String!
  modifiedAt: String
  modifiedBy: String
  access: [Access]!
}


# type Query {

# }

type Mutation {
  touch(name: String!, where: String!): File
  rmFile(id: String!): File
}
