scalar Date

type User {
  _id: String!
  nick: String!
  name: String!
  password: String!
  email: String!
  birth: String!
  accessLevel: String
  active: Boolean
}

input UserInput {
  nick: String!
  name: String!
  password: String!
  email: String!
  birth: Date!
  accessLevel: String
  active: Boolean
}


type Query {
  login(nick: String!, password: String!): User
  users: [User]!
  # user(id: ID!): User
  user(nick: String!): User
}

type Mutation {
  createUser(data: UserInput!): User!
  updateUser(id: ID, data: UserInput!): User!
}
